name: GitHub Pages

on:
  push:
    branches:
      - 'master'

jobs:
  pages:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
        with:
          persist-credentials: false

      - name: Setup PHP
        uses: shivammathur/setup-php@f3e473d116dcccaddc5834248c87452386958240 # 2.37.2
        with:
          php-version: '8.3'
          coverage: none

      - name: Install Dependencies
        run: composer install --no-progress --no-interaction --no-dev

      - name: Build Pages
        run: bin/apigen --title ApiGen src

      - name: Publish Pages
        uses: JamesIves/github-pages-deploy-action@6c2d9db
        with:
          folder: api
          branch: gh-pages
